language: generic 
sudo: required
services:
  - docker

before_install:
- docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react npm run test

deploy:
  provider: elasticbeanstalk # aws-elasticbeanstalk 
  region: "india"   # region of your Elastic Beanstalk application
  app: "docker-react" # name of your Elastic Beanstalk application
  env: "docker-react-env" # name of your Elastic Beanstalk environment
  bucket_name: "docker-react-bucket-name" # name of your S3 bucket
  bucket_path: "docker-react-bucket-path" # path of your S3 bucket
  on:    #"success" # deploy only on successful tests
    branch: main # deploy only on master branch
  access_key_id: "access key"   ## ($AWS_ACCESS_kEY) aws access key id
  secret_access_key: "secret"   ## ("$AWS_SECRET_KEY")  aws secret access key

  ## $AWS_ACCESS_key , $AWS_SECRET_KEY are environment variables in travis
